name: flip_everest
description: Flutter Cross-Platform Webview Application made for Flipeverest Company.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  onesignal_flutter: ^5.0.4
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#02acb0"
  android_12:
    color: "#02acb0"
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
