name: Flutter Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Fix CocoaPods CDN and Repo
        run: |
          cd ios
          pod repo remove master || true
          pod repo add-cdn master https://cdn.cocoapods.org/ || true
          pod repo update

      - name: Build IPA
        run: flutter build ipa --no-codesign
